<a href="https://colab.research.google.com/github/829797siva/numpy-library-/blob/main/numpy_practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating numpy arrays:

In [1]:
import numpy as np
arr=np.zeros ([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
import numpy as np
arr=np.ones([3,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [12]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


indexing and slicing:

indexing:

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[2])
print(arr[5])
print(arr[-1])


1
3
6
9


slicing:

In [17]:
arr=np.array([1,2,3,4,5,8,6,12,36])
print(arr[3:3])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

[]
[1 2 3]
[ 4  5  8  6 12 36]
[ 1  3  5  6 36]
[36 12  6  8  5  4  3  2  1]


aggregate operations:

In [21]:
arr=np.array([1,85,62,3,5,66])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))

222
1
85
34.751498768638264
37.0
33.5


ATTRIBUTES:

In [27]:
import numpy as np
details=[[1,2,4,5,6],[5,6,9,8,4]]
show=np.array(details)
print(show)
print(show.shape)

[[1 2 4 5 6]
 [5 6 9 8 4]]
(2, 5)


In [28]:
import numpy as np
data=[[55,66,99,88,66,55],[55,66,99,44,25,36]]
shap=np.array(data)
print(shap)
print(shap.ndim)

[[55 66 99 88 66 55]
 [55 66 99 44 25 36]]
2


In [29]:
import numpy as np
data=[[42,55,62,35,86],[8,5,9,6,4]]
show=np.array(data)
print(show)
print(show.T)

[[42 55 62 35 86]
 [ 8  5  9  6  4]]
[[42  8]
 [55  5]
 [62  9]
 [35  6]
 [86  4]]


importent methods in DATA SCIENCE:

In [30]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.reshape(5,2))


[[44 53]
 [95 65]
 [11 45]
 [78 95]
 [68 99]]


In [31]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.flatten())

[44 53 95 65 11 45 78 95 68 99]


In [32]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.ravel())

[44 53 95 65 11 45 78 95 68 99]


In [33]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.transpose())

[[44 45]
 [53 78]
 [95 95]
 [65 68]
 [11 99]]


In [34]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.sort())

None


In [35]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.argsort())

[[4 0 1 3 2]
 [0 3 1 2 4]]


In [37]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.diagonal())

[44 78]


In [38]:
import numpy as np
data=np.array([[44,53,95,65,11],[45,78,95,68,99]])
print(data.trace())

122
