<a href="https://colab.research.google.com/github/829797siva/numpy-library-/blob/main/project1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Matrix Operations Calculator

Goal: Create a program that performs matrix operations like addition, subtraction, multiplication, and transpose.

Concepts Used:

numpy.array()

numpy.dot()

numpy.transpose()

Example Tasks:

Take two matrices as input.

Perform operations and display results.

Validate shapes before multiplication.

Learning Outcome: Understand linear algebra basics using NumPy.

In [ ]:
import numpy as np
d1=np.array([[10,20,30,40,50],[50,40,60,60,40]])
d2=np.array([[40,50,20,80,90],[55,44,88,99,77]])
print(d1)
print(d2)
print("additon of two matrix:",d1+d2)
print("subtraction of two matrix:",d1-d2)
print("multiplication of two matrix:",d1*d2)
print("transpose of first matrix:",np.transpose(d1))
print("transpose of second matrix:",np.transpose(d2))
print(np.dot(10,2))
print(np.array(10))


[[10 20 30 40 50]
 [50 40 60 60 40]]
[[40 50 20 80 90]
 [55 44 88 99 77]]
additon of two matrix: [[ 50  70  50 120 140]
 [105  84 148 159 117]]
subtraction of two matrix: [[-30 -30  10 -40 -40]
 [ -5  -4 -28 -39 -37]]
multiplication of two matrix: [[ 400 1000  600 3200 4500]
 [2750 1760 5280 5940 3080]]
transpose of first matrix: [[10 50]
 [20 40]
 [30 60]
 [40 60]
 [50 40]]
transpose of second matrix: [[40 55]
 [50 44]
 [20 88]
 [80 99]
 [90 77]]
20
10
