<a href="https://colab.research.google.com/github/829797siva/numpy-library-/blob/main/project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Student Marks Analysis

Goal: Analyze marks of students in different subjects using NumPy arrays.

Concepts Used:

numpy.mean(), numpy.max(), numpy.min(), numpy.std()

Example Tasks:

Store marks of 5 students in 3 subjects.

Calculate average marks per student and per subject.

Find the topper in each subject.

Learning Outcome: Learn data summarization using NumPy statistics.

In [4]:
import numpy as np
marks=np.array([
    [77,78,98],
    [90,50,30],
    [100,80,100],
    [40,0,60],
    [70,50,60]
])
print(marks)

print("Average marks per student:")
print(np.mean(marks))
print("topper in each subject:")
print(np.max(marks))
print("Standard deviation per subject:")
print(np.std(marks))

[[ 77  78  98]
 [ 90  50  30]
 [100  80 100]
 [ 40   0  60]
 [ 70  50  60]]
Average marks per student:
65.53333333333333
topper in each subject:
100
Standard deviation per subject:
27.4441655406431
