<a href="https://colab.research.google.com/github/829797siva/numpy-library-/blob/main/project5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

5. Image Brightness Adjustment (Numerical Only)

Goal: Simulate increasing or decreasing brightness of a grayscale image.

Concepts Used:

numpy.clip()

numpy.add() or arithmetic operations

Example Tasks:

Represent a 5x5 image as a NumPy array (values between 0–255).

Add a constant to increase brightness.

Use np.clip() to ensure values stay within 0–255.

Learning Outcome: Understand how NumPy is used in image processing.

In [2]:
import numpy as np
image = np.array([
    [50, 80, 100, 120, 150],
    [60, 90, 110, 130, 160],
    [70, 100, 120, 140, 170],
    [80, 110, 130, 150, 180],
    [90, 120, 140, 160, 200]
])
print("Original Image:\n", image)
brightness_increase = 40
brighter_image = np.clip(image + brightness_increase, 0, 255)
brightness_decrease = 40
darker_image = np.clip(image - brightness_decrease, 0, 255)
print("\nBrighter Image:\n", brighter_image)
print("\nDarker Image:\n", darker_image)


Original Image:
 [[ 50  80 100 120 150]
 [ 60  90 110 130 160]
 [ 70 100 120 140 170]
 [ 80 110 130 150 180]
 [ 90 120 140 160 200]]

Brighter Image:
 [[ 90 120 140 160 190]
 [100 130 150 170 200]
 [110 140 160 180 210]
 [120 150 170 190 220]
 [130 160 180 200 240]]

Darker Image:
 [[ 10  40  60  80 110]
 [ 20  50  70  90 120]
 [ 30  60  80 100 130]
 [ 40  70  90 110 140]
 [ 50  80 100 120 160]]
